### ISSUE TITLE
Question about py-augest's capability of interacting with a splunk as a server side application.

### ISSUE THREAD

**Issue by IanB3** [snjoetw/py-august#10]
Hello,

I have a few questions on how this program works they are as follows:
1. Does the py-august program work only as a client side application or can it be modified to use on a server that uses Splunk?
2. How does one setup the values for the locks inside of the py-august application?
3. If the py-august application can work with a Splunk Server then is there any kind of communications from the august locks that need to be directed to the Splunk server?
4. How does one obtain the values of a august lock if the lock is already programmed and works?
5. Could you give me a brief organization of how the program's logic is supposed to flow to ensure that i didn't mess up any of the values and/or instructions in the program?

The reason why I'm asking is because I'm trying to make my Splunk server instance collect data on the people who are entering and exiting my house. If this idea can work then I hope to apply this idea to my place of work as a cyber security project for my internship course.

I would be more than happy if I could get help and guidance on this.

Thank you

**Comment by ehendrix23** [comment]
@IanB3 

I'll give my shot to answer. :-)

1. Not sure what you mean. In reality it is a client to the August portal to retrieve status or to set lock. You can import this module into your own Python code and then leverage it. For example, Home Assistant is a server application (home-assistant/home-assistant) that uses this module (see 
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/august.py, 
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/august.py, and 
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/lock/august.py

2. It actually retrieves all this information from the August account. Your August account will have locks  related to it. The module will just retrieve all the locks from the account provided.

3. If you want to get regular status updates into Splunk from August lock then you would want to write a Python program that does the calls to get the lock status update. That program can then, for example, just write it out to a log file and have Splunk then get the data from that log file.

4. See answer 2. August locks have to be already setup and attached to an August account. 

5. I just opened a new PR (https://github.com/snjoetw/py-august/pull/11) and in there I a Python program to test the performance changes (
https://github.com/snjoetw/py-august/files/2507707/August_Test.py.txt). Check that out. It will show you the steps for initial authentication; get all the locks associated with the provided account; and then retrieve the lock status, door status, and lock details.

Hope this helps!

**Comment by ehendrix23** [comment]
@IanB3,

Not sure to which program your referring. What is provided here in py-august really would be more to be used in your own program.

How it normally works is that on the August Connect app one creates an account (or logs on if already an account with August). Then the app discovers your lock and your connect. At that time you link the lock with your connect. Now the lock is able to communicate information to August's servers on it's status, and it allows August's servers to send lock or unlock commands to your lock. So right now the lock & connect are linked to each other and the connect is linked to your account.

Now, you can lock/unlock or get status from anywhere as long as you are able to retrieve the information from August's servers. That is where py-august comes in as it has everything to be able to authenticate to August's servers and then be able to retrieve information or to send like lock/unlock.

For what you wanna do, I would write a small Python program that just uses py-august (see the program I send that would already be close to what you need). 
Now you have 2 options to solve this:
  1. In your program you could just write an endless loop where you retrieve the lock information for all the locks and write that out to a CSV file or so; appending to it with current date/time. Once retrieved go to sleep for x amount of times and then retry.

  2. Call your program through a scheduler (i.e. crontab) and only have it get the information once (thus no endless loop).

Configure Splunk to retrieve the information from the CSV file.

For filename I would include current date so that you create a new file every day. Then have something to delete files older then y number of days.

Hope this helps!
