### ISSUE TITLE
Wakeup Doorbell - Can this be used to get latest image from doorbell?

### ISSUE THREAD

**Issue by 2016for** [snjoetw/py-august#13]
Was going through api.py and saw this. WAKEUP url.
Was wondering if this could be used to get the latest image from Doorbell?
If so would love to find out a way to integrate this into Home Assistant?
I mean would love to be able to refresh doorbell cam image manually on HA and maybe use this in some sort of automations as well

Thanks.

**Comment by snjoetw** [comment]
I've tried it when I added the integration initially but couldn't get it to refresh the camera image.

Now that it's been a while since I wrote this initially, maybe things are changed.
Are you able to test it by calling WAKEUP API manually and see if it triggers a refresh? I no longer have the doorbell so couldn't test it myself.
